name: 🐛 QA 버그 리포트
description: QA 테스트 중 발견된 버그를 보고합니다
title: "[QA-BUG] "
labels: ["qa", "bug", "needs-triage"]
assignees:
  - qa-team
body:
  - type: markdown
    attributes:
      value: |
        QA 테스트 중 발견된 버그를 상세히 기록해주세요.
        
  - type: dropdown
    id: severity
    attributes:
      label: 심각도
      description: 버그의 심각도를 선택하세요
      options:
        - Critical - 서비스 불가
        - High - 주요 기능 오류
        - Medium - 일부 기능 오류
        - Low - 사소한 오류
    validations:
      required: true
      
  - type: dropdown
    id: environment
    attributes:
      label: 테스트 환경
      description: 버그가 발생한 환경을 선택하세요
      options:
        - Production
        - Staging
        - Development
        - Local
    validations:
      required: true
      
  - type: input
    id: device
    attributes:
      label: 디바이스/브라우저
      description: 테스트한 디바이스와 브라우저 정보
      placeholder: "예: iPhone 13 / Safari 16.0"
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: 버그 설명
      description: 발견된 버그를 상세히 설명해주세요
      placeholder: |
        1. 무엇을 시도했나요?
        2. 예상한 결과는 무엇이었나요?
        3. 실제로 무엇이 발생했나요?
    validations:
      required: true
      
  - type: textarea
    id: steps
    attributes:
      label: 재현 단계
      description: 버그를 재현하는 단계를 순서대로 작성해주세요
      placeholder: |
        1. 홈페이지 접속
        2. 로그인 버튼 클릭
        3. ...
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: 예상 동작
      description: 정상적으로 작동해야 하는 방식
    validations:
      required: true
      
  - type: textarea
    id: actual
    attributes:
      label: 실제 동작
      description: 실제로 발생한 동작
    validations:
      required: true
      
  - type: textarea
    id: screenshots
    attributes:
      label: 스크린샷/동영상
      description: 버그 관련 스크린샷이나 동영상 링크를 첨부하세요
      placeholder: 이미지를 드래그 앤 드롭하거나 링크를 입력하세요
      
  - type: textarea
    id: additional
    attributes:
      label: 추가 정보
      description: 기타 도움이 될 만한 정보 (콘솔 로그, 네트워크 에러 등)
      
  - type: checkboxes
    id: checklist
    attributes:
      label: 체크리스트
      options:
        - label: 이미 보고된 이슈인지 확인했습니다
          required: true
        - label: 재현 가능한 버그입니다
          required: true