name = "gameplaza-db-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Default (development)
[[d1_databases]]
binding = "DB"
database_name = "gameplaza-development"
database_id = "d8bb6ff7-b731-4d5a-b22f-4b3e41c9ed8e"

# KV cache (development)
[[kv_namespaces]]
binding = "CACHE"
id = "3aaf9a0e37ae4a80baa64ce14e104d1c"

[env.production]
name = "gameplaza-db-api"

[[env.production.d1_databases]]
binding = "DB"
database_name = "gameplaza-production"
database_id = "1d59afcb-f4c2-4d1c-9532-a63bd124bf97"

# KV cache (production)
[[env.production.kv_namespaces]]
binding = "CACHE"
id = "766f8df2d323478791ebb2caff36662b"
