name = "gameplaza-db-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Default (development)
[[d1_databases]]
binding = "DB"
database_name = "gameplaza-development"
database_id = "d8bb6ff7-b731-4d5a-b22f-4b3e41c9ed8e"

[env.production]
name = "gameplaza-db-api"

[[env.production.d1_databases]]
binding = "DB"
database_name = "gameplaza-production"
database_id = "1d59afcb-f4c2-4d1c-9532-a63bd124bf97"

# Optional KV cache binding (create via: npx wrangler kv namespace create GAMEPLAZA_DB_API_CACHE)
[[kv_namespaces]]
binding = "CACHE"
# id = "<your-dev-kv-namespace-id>"  # fill after creation

[[env.production.kv_namespaces]]
binding = "CACHE"
# id = "<your-prod-kv-namespace-id>"  # fill after creation
