openapi: 3.0.0
info:
  title: 게임플라자 시간대 관리 API v2
  description: 관리자가 설정하는 시간대 예약 시스템 API
  version: 2.0.0

paths:
  /time-slots:
    get:
      tags:
        - time-slots
      summary: 시간대 목록 조회
      description: 등록된 시간대 템플릿 목록을 조회합니다
      parameters:
        - name: type
          in: query
          description: 시간대 유형
          schema:
            type: string
            enum: [default, custom]
        - name: active
          in: query
          description: 활성화 여부
          schema:
            type: boolean
      responses:
        '200':
          description: 시간대 목록
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/TimeSlotTemplate'
    
    post:
      tags:
        - time-slots
      summary: 시간대 템플릿 생성
      description: 새로운 시간대 템플릿을 생성합니다 (관리자 전용)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - startHour
                - endHour
                - price
              properties:
                name:
                  type: string
                  description: 시간대 이름 (예: "조기", "주간")
                description:
                  type: string
                  description: 시간대 설명
                startHour:
                  type: integer
                  minimum: 0
                  maximum: 29
                  description: 시작 시간 (0-29)
                endHour:
                  type: integer
                  minimum: 1
                  maximum: 30
                  description: 종료 시간 (1-30)
                price:
                  type: integer
                  minimum: 0
                  description: 시간대 가격
                type:
                  type: string
                  enum: [default, custom]
                  default: custom
                priority:
                  type: integer
                  default: 0
                  description: 우선순위 (높을수록 우선)
                active:
                  type: boolean
                  default: true
      responses:
        '201':
          description: 시간대 템플릿 생성 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimeSlotTemplate'
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /time-slots/{id}:
    get:
      tags:
        - time-slots
      summary: 시간대 템플릿 상세 조회
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 시간대 템플릿 정보
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimeSlotTemplate'
        '404':
          description: 시간대를 찾을 수 없음
    
    put:
      tags:
        - time-slots
      summary: 시간대 템플릿 수정
      description: 시간대 템플릿 정보를 수정합니다 (관리자 전용)
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                price:
                  type: integer
                priority:
                  type: integer
                active:
                  type: boolean
      responses:
        '200':
          description: 수정 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimeSlotTemplate'
        '404':
          description: 시간대를 찾을 수 없음
    
    delete:
      tags:
        - time-slots
      summary: 시간대 템플릿 삭제
      description: 시간대 템플릿을 삭제합니다 (관리자 전용)
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: 삭제 성공
        '404':
          description: 시간대를 찾을 수 없음

  /time-slots/schedules:
    get:
      tags:
        - time-slots
      summary: 시간대 스케줄 조회
      description: 특정 날짜 범위의 시간대 스케줄을 조회합니다
      parameters:
        - name: startDate
          in: query
          required: true
          description: 시작 날짜
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          required: true
          description: 종료 날짜
          schema:
            type: string
            format: date
        - name: deviceTypeId
          in: query
          description: 기기 종류 ID
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 시간대 스케줄
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/TimeSlotSchedule'
    
    post:
      tags:
        - time-slots
      summary: 시간대 스케줄 설정
      description: 특정 날짜의 시간대 스케줄을 설정합니다 (관리자 전용)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - date
                - deviceTypeId
                - timeSlotIds
              properties:
                date:
                  type: string
                  format: date
                  description: 적용 날짜
                deviceTypeId:
                  type: string
                  format: uuid
                  description: 기기 종류 ID
                timeSlotIds:
                  type: array
                  items:
                    type: string
                    format: uuid
                  description: 적용할 시간대 템플릿 ID 목록
                repeat:
                  type: object
                  description: 반복 설정
                  properties:
                    type:
                      type: string
                      enum: [daily, weekly, monthly]
                    endDate:
                      type: string
                      format: date
                    daysOfWeek:
                      type: array
                      items:
                        type: integer
                        minimum: 0
                        maximum: 6
                      description: 요일 (0=일요일, 6=토요일)
      responses:
        '201':
          description: 스케줄 설정 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TimeSlotSchedule'

  /time-slots/available:
    get:
      tags:
        - time-slots
      summary: 예약 가능한 시간대 조회
      description: 특정 날짜와 기기의 예약 가능한 시간대를 조회합니다
      parameters:
        - name: date
          in: query
          required: true
          description: 조회할 날짜
          schema:
            type: string
            format: date
        - name: deviceId
          in: query
          required: true
          description: 기기 ID
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 예약 가능한 시간대 목록
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        timeSlot:
                          $ref: '#/components/schemas/TimeSlotTemplate'
                        available:
                          type: boolean
                          description: 예약 가능 여부
                        remainingSlots:
                          type: integer
                          description: 남은 예약 가능 수
                        price:
                          type: integer
                          description: 해당 시간대 가격

components:
  schemas:
    TimeSlotTemplate:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          description: 시간대 이름
        description:
          type: string
          description: 시간대 설명
        startHour:
          type: integer
          description: 시작 시간 (0-29)
        endHour:
          type: integer
          description: 종료 시간 (1-30)
        displayTime:
          type: string
          description: 표시용 시간 (예: "07:00 - 12:00")
        duration:
          type: integer
          description: 시간대 길이 (시간)
        price:
          type: integer
          description: 가격
        type:
          type: string
          enum: [default, custom]
          description: 시간대 유형
        priority:
          type: integer
          description: 우선순위
        active:
          type: boolean
          description: 활성화 여부
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    
    TimeSlotSchedule:
      type: object
      properties:
        id:
          type: string
          format: uuid
        date:
          type: string
          format: date
          description: 적용 날짜
        deviceTypeId:
          type: string
          format: uuid
          description: 기기 종류 ID
        timeSlots:
          type: array
          items:
            $ref: '#/components/schemas/TimeSlotTemplate'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        details:
          type: object