name: E2E on Vercel Preview (label: e2e:preview)

on:
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  e2e-preview:
    if: contains(github.event.pull_request.labels.*.name, 'e2e:preview')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR head
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Find Vercel Preview URL from PR comments
        id: find
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request
            const { owner, repo } = context.repo
            const { data: comments } = await github.rest.issues.listComments({ owner, repo, issue_number: pr.number, per_page: 100 })
            const regex = /https?:\/\/[^\s]*vercel\.app[^\s]*/ig
            let url = null
            for (const c of comments) {
              const m = c.body && c.body.match && c.body.match(regex)
              if (m && m.length) { url = m[0]; break }
            }
            if (!url) {
              core.setFailed('Vercel Preview URL not found in PR comments')
            } else {
              core.setOutput('preview_url', url)
            }

      - name: Run smoke E2E against Preview
        env:
          CI: true
          BASE_URL: ${{ steps.find.outputs.preview_url }}
        run: npx playwright test -c playwright.smoke.config.ts tests/e2e/specs/smoke.spec.ts

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-preview
          path: playwright-report

